---
- hosts: raspi
  become: true
  vars:
    - install_modules: [python3-pip]
    - install_pymodules: [mh_z19]
  tasks:
    - name: install pip # task
      apt: # task内で指定するモジュール
        name: "{{ install_modules }}" # モジュールに対して指定するパラメータ
        state: latest

    - name: install python3-install_modules
      pip:
        name: "{{ install_pymodules}}"
        state: latest

